### ISSUE TITLE
Проверка лабораторной работы 4

### ISSUE THREAD

**Issue by DX37** [DX37/Lab4#1]
Работу выполнил:
* Курносенко Максим Сергеевич

To: @evgeny-p

**Comment by evgeny-p** [comment]
1. В `.gitignore` происходит что-то стнанное. Первая строчка говорит о том, что каталог `bin` не нужно игнорировать. Вторая — что содержимое каталога `bin` все-таки нужно игнорировать.

1. В заголовочном файле отсутствуют [include guards](https://ru.wikipedia.org/wiki/Include_guard).

1. Согласно сообщению в последнем коммите, Вы предерживаетесь [Qt Coding Style](https://wiki.qt.io/Qt_Coding_Style). Обратите внимание на пункт «Exception 2: Brace symmetry».

1. Имена файлов `func.[ch]` слишком обобщенные.

1. Не обязательно к исправлению: в мейкфайле создание директорий можно было бы вынести в отдельную цель и указать ее в качестве первой зависимости к основной цели. Таким образом, подготовка рабочего каталога будет отделена от компиляции.

1. На будущее: компилировать нужно с опцией `-Wall`.

Задание со звездочкой. В мастере есть серия коммитов, затрагивающих `.gitignore`. И будет еще один с исправлением замечания. Историю ветки `master` можно переписать, объединив коммиты с изменениями `.gitignore` в один. Результирующая история будет выглядеть так, как будто в репозитории сразу была корректная версия. Для этого понадобится команда `git rebase` с опцией `--interactive`, а пуш нужно будет выполнить с опцией `--force`.

Обычно переписывать историю ветки `master` не рекомендуется, как и любой ветки, в которой одновременно работает несколько человек. В этом еще одно преимущество работы в отдельных ветках: перед мержем в мастер их историю можно многократно переписывать, не мешая коллегам. В данном случае в репозитории работаете только Вы, поэтому в учебных целях переписывание истории мастера допускается.
